language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run build

before_install:
- openssl aes-256-cbc -K $encrypted_d20951817539_key -iv $encrypted_d20951817539_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

addons:
  ssh_known_hosts: 159.65.165.38

deploy:
  provider: script
  skip_cleanup: true
  script: rsync $TRAVIS_BUILD_DIR/dist/* ada@159.65.165.38:/var/www/html
  on:
    branch: prod

    rsync --quiet ./dist ada@159.65.165.38:/var/www/html